### ISSUE TITLE
Chicken and egg problem with Tails

### ISSUE THREAD

**Issue by andyleclair** [frankdugan3/phlegethon#19]
hi! I'm following the install instructions, and I've run into a situation I can't seem to find my way out of. I can compile `tails` without setting `colors_file`, but when I try to do `mix phlegethon.setup`  after setting the colors file, I get:

```
== Compilation error in file lib/tails.ex ==
** (File.Error) could not read file "/home/axe/src/garage/assets/tailwind.phlegethon.colors.json": no such file or directory
    (elixir 1.14.3) lib/file.ex:358: File.read!/1
    lib/tails.ex:3: (module)
could not compile dependency :tails, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile tails", update it with "mix deps.update tails" or clean it with "mix deps.clean tails"
```

Do I need to generate a default first?

**Comment by frankdugan3** [comment]
Sorry, I should have mentioned that in the README. If you run `./setup.sh`, that script will create a dummy colors file.

I'm thinking about a better way to deal with this in the future.

**Comment by andyleclair** [comment]
That did it! I can PR in an update to the readme, if you'd like?

**Comment by frankdugan3** [comment]
Appreciate the offer, but I *think* my plan is to remove the requirement for a colors file and remove that feature from the Phlegethon theme so you can just run w/ the default colors. I'll change the instructions to reflect that, and it should also speed up the compilation. Will take me a little while because I have to refactor the themes to not rely on the `brand` and `brand-fg` colors.

**Comment by andyleclair** [comment]
Ok! Thanks for the answer, I'll close this then

**Comment by frankdugan3** [comment]
No problem. Just pushed a major colors refactor and updated the `get-started.md` guide. You don't need the `colors.json` file or the Tails config anymore. If you remove it, you will need to force a tails recompile with `mix deps.compile tails --force`.
